lib/components/discounts/widget/discounts_filter_widget.dart, lib/components/discounts/widget/discounts_widget_list.dart, macos/Flutter/GeneratedPluginRegistrant.swift
=> discount list fix findChildIndexCallback

lib/components/discounts/widget/discounts_widget_list.dart, lib/components/home/widget/faq_section_widget.dart, lib/components/home/widget/home_section_widget.dart, lib/components/home/widget/question_widget_list.dart, lib/components/investors/widget/funds_widget_list.dart, web/index.html
=> fix: home page ui

lib/components/discounts/widget/discounts_widget_list.dart, lib/components/discounts_add/bloc/discounts_add_bloc.dart, lib/components/discounts_add/field_models/eligibility_field_model.dart, lib/shared/constants/enum.dart, lib/shared/constants/text/text_constants.dart, lib/shared/extension/extension_dart_constants.dart, lib/shared/extension/extension_flutter_constants.dart, lib/shared/extension/list_extension_dart.dart, lib/shared/models/discount_model.dart, test/constants.dart
=> feat: discount model use enum for eligibility field

lib/shared/models/discount_model.dart
=> eligiblity add default value

lib/shared/constants/text/text_constants.dart, lib/shared/data_provider/firestore_provider.dart
=> add admin account to business site

lib/components/discounts/widget/discounts_filter_mob.dart, lib/shared/models/failure_model/exceptions.dart, lib/shared/models/failure_model/some_failure_model.dart, lib/shared/repositories/app_authentication_repository.dart, lib/shared/repositories/device_repository.dart, lib/shared/repositories/failure_repository.dart, lib/shared/repositories/url_repository.dart, test/login/login_widget_test.dart, test/sign_up/sign_up_widget_test.dart
=> fix: sentry error

lib/components/discounts_add/bloc/discounts_add_bloc.dart, lib/shared/constants/text/text_constants.dart, lib/shared/extension/extension_dart_constants.dart, lib/shared/extension/list_extension_dart.dart, lib/shared/models/discount_model.dart, lib/shared/repositories/discount_filter_repository.dart, test/constants.dart, test/discounts/unit_test/discount_model_test.dart
=> fix: eligibility all state in filter

lib/components/home/widget/body/home_body_widget.dart
=> fix: add padding under footer

lib/components/discounts_add/bloc/discounts_add_bloc.dart, lib/shared/extension/extension_dart_constants.dart, lib/shared/extension/extension_flutter_constants.dart
=> admin company not change company data when edit discount

lib/shared/repositories/discount_filter_repository.dart
=> user can active only one filter

lib/app.dart, lib/bootstrap.dart, lib/shared/navigation/business_router_go.dart, lib/shared/navigation/router_go_mob.dart, lib/shared/navigation/router_go_web.dart, lib/shared/repositories/discount_filter_repository.dart
=> chanege page builder to builder and remove switch page delay

lib/app.dart, lib/bootstrap.dart, lib/shared/navigation/business_router_go.dart, lib/shared/navigation/router_go_mob.dart, lib/shared/navigation/router_go_web.dart, lib/shared/repositories/discount_filter_repository.dart
=> Change page builder to builder

lib/components/discounts/widget/advanced_filter/advanced_filter_content.dart, lib/components/discounts/widget/advanced_filter/advanced_filter_hide_list_widget.dart, lib/components/discounts/widget/body/discounts_body_widget.dart, lib/components/investors/widget/body/investors_body_widget.dart, lib/components/investors/widget/investors_description_widget.dart, lib/components/investors/widget/investors_title_widget.dart, lib/shared/extension/list_extension_flutter.dart, lib/shared/widget/cancel_chip_widget.dart
=> filter adjustment

lib/components/discount/widget/discount_information_widget.dart, lib/components/discounts/widget/advanced_filter/advanced_filter_content.dart, lib/components/discounts/widget/advanced_filter/advanced_filter_hide_list_widget.dart, lib/components/discounts/widget/discounts_widget_list.dart, lib/shared/widget/cancel_chip_widget.dart, lib/shared/widget/check_point_widget.dart, lib/shared/widget/row_sliver_widget.dart, lib/shared/widget/tooltip_widget.dart
=> change custom row sliver to standart flutter row sliver

lib/components/discounts_add/bloc/discounts_add_bloc.dart, lib/shared/constants/text/text_constants.dart, lib/shared/extension/extension_flutter_constants.dart, lib/shared/models/convertors/images_convertor.dart, lib/shared/models/convertors/translate_convertor.dart, lib/shared/models/discount_model.dart, lib/shared/models/funds_model.dart, lib/shared/models/question_model.dart, lib/shared/widget/question_widget.dart, lib/shared/widget/row_sliver_widget.dart, test/constants.dart, test/discounts/unit_test/discount_model_test.dart, test/home/unit_test/home_model_test.dart
=> remove read value function

README.md
=> Update README.md License

lib/components/discount/widget/body/discount_body_widget.dart, lib/components/discount/widget/discount_information_widget.dart, lib/components/discounts/widget/body/discounts_body_widget.dart, lib/components/discounts/widget/discount_title_widget.dart, lib/components/feedback/widget/feedback_title.dart, lib/components/investors/widget/body/investors_body_widget.dart, lib/components/investors/widget/investors_title_widget.dart, lib/components/login/widget/body/login_body_widget.dart, lib/components/profile/widget/body/profile_body_widget.dart, lib/components/sign_up/widget/body/sign_up_body_widget.dart, lib/shared/constants/dimensions/padding_constants.dart, lib/shared/navigation/business_router_go.dart, lib/shared/navigation/router_go_mob.dart, lib/shared/navigation/router_go_web.dart, lib/shared/widget/scaffold_widget.dart, lib/shared/widget/title_widgets.dart
=> fix mobile adjustment

lib/components/discounts/widget/advanced_filter/advanced_filter_content.dart, lib/components/discounts/widget/advanced_filter/advanced_filter_hide_list_widget.dart
=> filter adjustmand return previous logic for desk

.fvmrc, .github/workflows/ci_build_and_test.yaml, .github/workflows/integration_web_chrome_tests.yaml, lib/shared/widget/network_image_widget.dart, pubspec.lock
=> Flutter version 3.27.1

lib/components/discounts/widget/discount_sorting_widget.dart, lib/components/login/widget/body/login_body_widget.dart, lib/components/sign_up/widget/body/sign_up_body_widget.dart, lib/shared/constants/style/text_styles.dart, lib/shared/widget/box_widget.dart, lib/shared/widget/button_widget.dart, lib/shared/widget/cancel_chip_widget.dart, lib/shared/widget/check_point_widget.dart, lib/shared/widget/confirm_publish_discount_dialog.dart, lib/shared/widget/discount_text_widget.dart, lib/shared/widget/donate_button_widget.dart
=> remove google sing in for mobile and fix support text

lib/components/password_reset/view/password_reset_view.dart, lib/components/password_reset/widget/body/password_reset_body_widget.dart, lib/shared/bloc/url/url_cubit.dart, lib/shared/constants/text/url_parameters.dart, lib/shared/extension/extension_dart_constants.dart, lib/shared/navigation/router_go_web.dart, lib/shared/repositories/app_authentication_repository.dart, lib/shared/repositories/i_url_repository.dart, lib/shared/repositories/url_repository.dart, lib/shared/widget/email_password_fields_widget.dart
=> add reset password button to prod

lib/components/password_reset/widget/body/password_reset_body_widget.dart, lib/shared/bloc/url/url_cubit.dart, lib/shared/navigation/router_go_mob.dart, lib/shared/repositories/i_url_repository.dart, lib/shared/repositories/url_repository.dart
=> mob add reset password path

lib/components/discount/widget/body/discount_body_widget.dart, lib/components/discount/widget/widget.dart, lib/components/feedback/widget/body/feedback_body_widget.dart, lib/components/feedback/widget/feedback_form_state_widget.dart, lib/components/feedback/widget/feedback_title.dart, lib/components/home/widget/home_section_widget_list.dart, lib/components/password_reset/bloc/check_code/check_verification_code_cubit.dart, lib/components/password_reset/widget/blocprovider/password_reset_blocprovider.dart, lib/components/password_reset/widget/body/password_reset_body_widget.dart, lib/components/pw_reset_email/widget/body/pw_reset_email_body_widget.dart, lib/l10n/arb/app_en.arb, lib/l10n/arb/app_uk.arb, lib/shared/bloc/url/url_cubit.dart, lib/shared/constants/route_constants.dart, lib/shared/navigation/business_router_go.dart, lib/shared/navigation/router_go_mob.dart, lib/shared/navigation/router_go_web.dart, lib/shared/repositories/app_authentication_repository.dart, lib/shared/repositories/i_url_repository.dart, lib/shared/repositories/url_repository.dart, lib/shared/widget/back_button_widget.dart, lib/shared/widget/confirm_publish_discount_dialog.dart, lib/shared/widget/email_password_fields_widget.dart, lib/shared/widget/widget.dart, test/helpers/widget/email_password_fields/email_password_fields_navigation_helper.dart, test/login/login_widget_test.dart, test/password_reset/helper/wrong_code_navigation_helper.dart, test/password_reset/password_reset_widget_test.dart
=> Mob add reset password page

lib/components/company/widget/body/company_body_widget.dart, lib/components/discounts/widget/body/discounts_body_widget.dart, lib/components/discounts/widget/discount_title_widget.dart, lib/components/feedback/widget/feedback_title.dart, lib/components/login/widget/body/login_body_widget.dart, lib/components/mob_settings/widget/body/mob_settings_body.dart, lib/components/password_reset/widget/body/password_reset_body_widget.dart, lib/components/profile/widget/body/profile_body_widget.dart, lib/components/pw_reset_email/widget/body/pw_reset_email_body_widget.dart, lib/components/sign_up/widget/body/sign_up_body_widget.dart, lib/shared/widget/menu_dialog_widget.dart, lib/shared/widget/title_widgets.dart
=> change divider color and fix web forgot password app bar

lib/components/discount/bloc/discount_watcher_bloc.dart, lib/components/discount_card/bloc/discount_card_watcher_cubit.dart, lib/components/discounts/bloc/watcher/discounts_watcher_bloc.dart, lib/shared/constants/text/remote_config_key.dart, lib/shared/constants/text/text.dart, lib/shared/data_provider/firebase_remote_config_provider.dart, lib/shared/data_provider/firestore_provider.dart, lib/shared/repositories/discount_repository.dart, lib/shared/repositories/i_discount_repository.dart
=> add remote config value show to mob only business add discounts

lib/components/discounts/bloc/watcher/discounts_watcher_bloc.dart, lib/shared/repositories/app_authentication_repository.dart, lib/shared/widget/back_button_widget.dart, test/app/app_widget_test.dart, test/company/unit_test/company_discounts_repository_test.dart, test/data_provider/firestore/firestore_provider_discounts_test.dart, test/discount_card/discount_card_unit_test.dart, test/discount_card/discount_card_widget_test.dart, test/discounts/discounts_mob_widget_test.dart, test/discounts/discounts_widget_test.dart, test/discounts/unit_test/discount_bloc_test.dart, test/discounts/unit_test/discount_repository_test.dart, test/discounts_add/discounts_add_unit_test.dart, test/discounts_add/discounts_add_widget_test.dart, test/discounts_add/discounts_edit_widget_test.dart, test/my_discounts/unit_test/discounts_repository_test.dart
=> fix test error problems

lib/shared/constants/theme/widget_theme.dart
=> discount card change border color

lib/components/discounts/widget/advanced_filter/advanced_filter_mob_button.dart
=> advanced filter add bottom padding for mobile keyboard

lib/components/discounts/bloc/config/discount_config_cubit.dart, lib/components/discounts/bloc/config/discount_config_state.dart, lib/components/discounts/widget/advanced_filter/advanced_filter_hide_list_widget.dart, lib/components/discounts/widget/advanced_filter/advanced_filter_mob_button.dart, lib/components/discounts/widget/blocprovider/advanced_filter_mob_blocprovider.dart, lib/shared/constants/text/remote_config_key.dart, test/discounts/unit_test/discount_config_cubit_test.dart
=> Add mob filter enhanced mobile key

lib/components/discounts/bloc/bloc.dart, lib/components/discounts/bloc/view_mode/view_mode_cubit.dart, lib/components/discounts/bloc/view_mode_cubit.dart, lib/components/discounts/widget/blocprovider/discounts_blocprovider.dart, lib/components/discounts/widget/body/discounts_body_widget.dart, lib/components/discounts/widget/discount_title_widget.dart, lib/components/discounts/widget/discounts_widget_list.dart, lib/shared/constants/style/button_constants.dart, lib/shared/constants/widget/icon_constants.dart, lib/shared/widget/discount_card_widget.dart, pubspec.lock, pubspec.yaml
=> feat: vertical discount cards

lib/components/discounts/bloc/watcher/discounts_watcher_bloc.dart, lib/components/discounts/widget/advanced_filter/advanced_filter_content.dart, lib/components/discounts/widget/advanced_filter/advanced_filter_hide_list_widget.dart, lib/shared/constants/theme/app_colors.dart, lib/shared/widget/cancel_chip_widget.dart, lib/shared/widget/check_point_widget.dart
=> prototype list remove padding

lib/components/discount/widget/discount_information_widget.dart, lib/shared/constants/style/button_constants.dart, lib/shared/widget/discount_eligibility_widget.dart, lib/shared/widget/discount_text_widget.dart
=> fix: change of eligibility

test/bloc/app_version/app_version_cubit_test.dart, test/bloc/authentication/authentication_bloc_test.dart, test/bloc/company/company_bloc_test.dart, test/bloc/mob_offline_mode_cubit_test.dart, test/investors/unit_test/investors_model_test.dart, test/repository/device/device_repository_test.dart, test/test_dependency_injector.dart, test/test_mocks/discount_init_register.dart, test/test_mocks/test_mocks.dart, test/test_mocks/user_setting_register.dart
=> test: fix failure for start

lib/shared/widget/network_image_widget.dart, test/helpers/widget/confirm_dialog/confirm_dialog_unconfim_helper.dart
=> test: fix profile tests

lib/components/discounts/widget/advanced_filter/advanced_filter_content.dart, lib/components/feedback/widget/feedback_form_state_widget.dart, lib/shared/bloc/network/network_cubit.dart, lib/shared/constants/widget/icon_constants.dart, lib/shared/widget/footer_widget.dart, lib/shared/widget/network_banner.dart, lib/shared/widget/shared_icon_list_widget.dart, test/constants.dart, test/helpers/scrolling_helper.dart, test/helpers/widget/dialogs/dialogs_failure_get_helper.dart, test/helpers/widget/failure_loading_helper.dart, test/helpers/widget/footer/footer_helper.dart, test/home/helper/home_failure_helper.dart, test/home/home_widget_test.dart, test/my_discounts/unit_test/my_discounts_bloc_test.dart
=> test: fix test and fix network banner

lib/components/discount/view/discount_view_widget.dart, lib/components/discounts/view/discounts_view.dart, lib/components/feedback/view/feedback_view.dart, lib/components/home/view/home_view.dart, lib/components/investors/view/investors_view.dart, lib/shared/widget/scaffold_auto_loading_widget.dart, lib/shared/widget/scaffold_widget.dart
=> feat: dd ColoredBox for ios safe area

lib/components/discounts/bloc/config/discount_config_cubit.dart, lib/components/discounts/widget/advanced_filter/advanced_filter_hide_list_widget.dart, lib/shared/widget/cancel_chip_widget.dart
=> hide filter icon when mobile has chosen item

lib/components/discounts/bloc/config/discount_config_cubit.dart, lib/components/discounts/bloc/config/discount_config_state.dart, lib/components/discounts/widget/discount_title_widget.dart, test/discounts/unit_test/discount_config_cubit_test.dart
=> feat: vertical card feature toggle

lib/components/discounts/widget/discounts_widget_list.dart, lib/shared/widget/discount_card_widget.dart, lib/shared/widget/shared_icon_list_widget.dart
=> feat: desk vertical card open desk url dialog

lib/bootstrap.dart, lib/components/discount/view/discount_view_widget.dart, lib/components/discounts/view/discounts_view.dart, lib/components/feedback/view/feedback_view.dart, lib/components/home/view/home_view.dart, lib/components/investors/view/investors_view.dart, lib/shared/constants/theme/app_colors.dart, lib/shared/widget/scaffold_auto_loading_widget.dart, lib/shared/widget/scaffold_widget.dart
=> fix: android last version fix status bar color

lib/components/discounts/widget/advanced_filter/advanced_filter_content.dart, lib/components/discounts/widget/advanced_filter/advanced_filter_mob_button.dart, lib/shared/constants/theme/app_colors.dart, lib/shared/widget/shared_icon_list_widget.dart
=> feat: mobile filter dialog fix bottom padding

lib/components/discounts/widget/discount_sorting_widget.dart, lib/shared/constants/style/button_constants.dart, lib/shared/widget/popup_menu_button_widget.dart
=> sorting widget change style for check item widget

lib/shared/widget/popup_menu_button_widget.dart, lib/shared/widget/shared_icon_list_widget.dart
=> popup button caculate auto position for meny

lib/shared/widget/network_image_widget.dart
=> fix: edit image in profile bug

lib/components/discounts/widget/body/discounts_body_widget.dart, lib/shared/widget/network_image_widget.dart
=> feat: comment rate dialog

lib/components/discounts/widget/discount_sorting_widget.dart, lib/shared/constants/style/button_constants.dart
=> feat: set max size for sort button

web/manifest.json
=> feat: prefer_related_applications set true in the manifest

.github/workflows/ci_build_and_test.yaml, lib/l10n/arb/app_en.arb, lib/l10n/arb/app_uk.arb, lib/shared/bloc/report/report_bloc.dart, lib/shared/bloc/report/report_state.dart, lib/shared/constants/theme/app_theme.dart, lib/shared/widget/report_dialog_widget.dart, test/bloc/report/report_bloc_test.dart
=> feat: report email field always required

.github/workflows/ci_build_and_test.yaml, test/discounts/unit_test/discount_bloc_test.dart
=> feat: add some discount bloc test

.github/workflows/ci_build_and_test.yaml, lib/shared/widget/dialogs_widget.dart
=> feat: add hide for snack bar

lib/components/discounts/widget/advanced_filter/advanced_filter.dart, lib/components/discounts/widget/advanced_filter/advanced_filter_content.dart, lib/components/discounts/widget/advanced_filter/city_search_field_widget.dart, lib/shared/widget/drop_list_field_widget.dart, lib/shared/widget/email_password_fields_widget.dart, lib/shared/widget/message_field_widget.dart, lib/shared/widget/password_field_widget.dart, lib/shared/widget/text_field_widget.dart
=> feat: city search add clear icon

.github/workflows/ci_build_and_test.yaml, lib/components/discounts/widget/advanced_filter/advanced_filter_mob_button.dart, lib/components/my_discounts/widget/my_discounts_card.dart, lib/shared/extension/extension_flutter_constants.dart, lib/shared/widget/confirm_dialog.dart, lib/shared/widget/confirm_publish_discount_dialog.dart, lib/shared/widget/menu_dialog_widget.dart, lib/shared/widget/mob_update_dialog.dart, lib/shared/widget/report_dialog_widget.dart, test/company/company_widget_test.dart, test/company/helper/buttons/log_out_unconfirm_button_helper.dart, test/company/helper/company_pump_app_helper.dart, test/helpers/widget/confirm_dialog/confirm_dialog_cancel_icon_dialog_helper.dart, test/helpers/widget/confirm_dialog/confirm_dialog_unconfim_helper.dart, test/helpers/widget/confirm_dialog/confirn_dialog_helper.dart, test/helpers/widget/menu_dialog_helper.dart, test/helpers/widget/nawbar/nawbar.dart, test/helpers/widget/nawbar/nawbar_menu_helper.dart, test/helpers/widget/nawbar/open_nawbar_menu_helper.dart, test/helpers/widget/report_dialog/report_dialog_correct_save_helper.dart, test/helpers/widget/report_dialog/report_dialog_helper.dart, test/profile/helper/buttons/log_out_unconfirm_button_helper.dart, test/profile/helper/profile_pump_app_helper.dart, test/profile/profile_widget_test.dart
=> test: test can close dialog

.gitignore, ios/Podfile.lock, ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, macos/Runner.xcodeproj/project.pbxproj, macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, macos/Runner/AppDelegate.swift, test/profile/profile_mobile_widget_test.dart, test/profile/profile_widget_test.dart
=> test: profile page coverage

lib/components/home/view/home_view.dart, test/home/helper/home_failure_helper.dart
=> test: home page coverage

lib/shared/bloc/authentication/authentication_bloc.dart, lib/shared/bloc/authentication/authentication_event.dart, lib/shared/bloc/authentication/authentication_state.dart, test/bloc/authentication/authentication_bloc_test.dart, test/bloc/authentication/authentication_repository_stream_test.dart
=> test: Authentication repositore/bloc coverage

test/discounts/unit_test/view_mode_cubit_test.dart
=> test: view mode cubit

lib/components/discounts_add/bloc/discounts_add_bloc.dart, lib/components/discounts_add/bloc/discounts_add_state.dart, lib/components/discounts_add/widget/body/discounts_add_body_widget.dart, lib/shared/constants/text/text_constants.dart, lib/shared/extension/extension_flutter_constants.dart, lib/shared/extension/list_extension_dart.dart, lib/shared/widget/confirm_publish_discount_dialog.dart, test/constants.dart, test/discounts_add_and_edit/discounts_add_unit_test.dart, test/discounts_add_and_edit/discounts_add_widget_test.dart, test/discounts_add_and_edit/discounts_edit_widget_test.dart, test/discounts_add_and_edit/helper/form/discounts_add_correct_helper.dart, test/discounts_add_and_edit/helper/form/discounts_add_uncorrect_helper.dart, test/discounts_add_and_edit/helper/form/discounts_description_enter_helper.dart, test/helpers/widget/dialogs/confirm_publish_discount_dialog_helper.dart, test/helpers/widget/dialogs/confirm_publish_discount_dialog_nav_helper.dart, test/helpers/widget/dialogs/dialogs.dart
=> test: discount add/edit

lib/shared/constants/text/text_constants.dart, lib/shared/extension/field_models_error_get.dart, lib/shared/models/convertors/images_convertor.dart, lib/shared/models/convertors/title_convertor.dart, lib/shared/models/field_models/multi_field_model.dart, lib/shared/models/question_model.dart, test/constants.dart, test/data_provider/firestore/firestore_provider_question_test.dart, test/discounts/discounts_dialogs_widget_test.dart, test/discounts/discounts_widget_test.dart, test/discounts/helper/advanced_filter/advanced_filter_close_open_items_helper.dart, test/discounts/helper/advanced_filter/advanced_filter_enachanced_mobile_helper.dart, test/discounts/helper/advanced_filter/advanced_filter_helper.dart, test/discounts/helper/advanced_filter/advanced_filter_reset_mob_helper.dart, test/discounts/helper/discounts_initial_helper.dart, test/discounts/unit_test/discount_model_test.dart, test/home/unit_test/home_model_test.dart, test/model/filter_model_test.dart, test/model/some_failure_model_test.dart
=> test: models

.github/workflows/coverage_push.yaml
=> push test coverage workflow

.github/workflows/push_code_coverage.yaml, lib/app.dart, lib/components/discount/widget/body/discount_body_widget.dart, lib/components/discount_card/view/diiscount_card_view.dart, lib/components/discounts/widget/body/discounts_body_widget.dart, lib/components/feedback/widget/body/feedback_body_widget.dart, lib/components/home/widget/body/home_body_widget.dart, lib/components/investors/widget/body/investors_body_widget.dart, lib/components/markdown_file_dialog/view/markdown_file_view.dart, lib/components/news_card/view/news_card_view.dart, lib/shared/bloc/app_layout/app_layout_bloc.dart, lib/shared/bloc/authentication/authentication_bloc.dart, lib/shared/bloc/bloc.dart, lib/shared/bloc/company/company_watcher_bloc.dart, lib/shared/bloc/user/user_watcher_bloc.dart, lib/shared/repositories/app_layout_repository.dart, lib/shared/repositories/i_app_layout_repository.dart, lib/shared/repositories/repositories.dart, lib/shared/shared_flutter.dart, lib/shared/widget/dialogs_widget.dart, lib/shared/widget/navigation_bar_widget.dart, test/bloc/layout/layout_cubit_test.dart, test/bloc/layout/layout_repository_test.dart, test/helpers/pump_app.dart, test/test_mocks/app_layout_cubit_register.dart, tests_quick.sh
=> test: layout bloc/repository

lib/shared/repositories/i_discount_filter_repository.dart
=> test: push code coverage

lib/shared/bloc/mob_feedback/mob_feedback_bloc.dart, lib/shared/bloc/mob_feedback/mob_feedback_event.dart, lib/shared/bloc/mob_feedback/mob_feedback_state.dart, lib/shared/bloc/user/user_watcher_bloc.dart, lib/shared/constants/widget_keys/widget/mob_feedback.dart, lib/shared/models/feedback_model.dart, lib/shared/widget/mob_feedback_widget.dart, test/bloc/mob_feedback_bloc_test.dart, test/constants.dart, test/feedback/unit_test/feedback_model_test.dart, test/helpers/widget/mob_feedback/mob_feedback_correct_text_helper.dart, test/helpers/widget/mob_feedback/mob_feedback_enter_text_helper.dart, test/helpers/widget/mob_feedback/mob_feedback_helper.dart, test/helpers/widget/mob_feedback/mob_feedback_wrong_text_helper.dart
=> feat: Add email for mob feedback

lib/components/feedback/bloc/feedback_bloc.dart, lib/components/feedback/widget/feedback_field_widget.dart, test/feedback/helper/feedback_register_helper.dart, test/feedback/unit_test/feedback_bloc_test.dart
=> feat: feedback hide email field if user sign in/up

lib/shared/repositories/app_authentication_repository.dart, lib/shared/widget/mob_navigation_widget.dart, lib/shared/widget/user_photo_widget.dart, test/repository/app_authentication/app_authentication_repository_success_test.dart, test/repository/app_authentication/app_authetication_failure_get_repository_test.dart, test/repository/app_authentication/app_authetication_failure_repository_test.dart
=> feat: change user stream when user changed(not only auth status)

lib/shared/extension/extension_dart_constants.dart, lib/shared/models/discount_model.dart, lib/shared/repositories/discount_repository.dart
=> feat: if discount edited remove rejected status

lib/components/consent_dialog/widget/body/consent_dialog_body.dart, lib/shared/repositories/secure_storage_module.dart
=> feat: flutter secure storage use web crypto

lib/components/consent_dialog/widget/body/consent_dialog_body.dart, lib/shared/constants/models.dart, test/repository/data_picker_repository_test.dart
=> feat: image picker support only image ecept gif format

.fvmrc, pubspec.lock, pubspec.yaml
=> feat: flutter version revert

lib/components/discounts/widget/discount_sorting_widget.dart, lib/components/user_role/widget/body/user_role_body_widget.dart, lib/shared/constants/models_flutter.dart, lib/shared/extension/extension_flutter_constants.dart, lib/shared/widget/drop_down_button_widget.dart, lib/shared/widget/popup_menu_button_widget.dart, lib/shared/widget/shared_icon_list_widget.dart, pubspec.lock, pubspec.yaml
=> feat: Popup menu widget user custom package

integration_test/business_add_discount_test.dart, integration_test/business_sign_up_test.dart, integration_test/sign_in_test.dart, integration_test/sign_up_test.dart, integration_tests.sh
=> fix: integration tests

ios/Podfile.lock, ios/Runner/Runner.entitlements, lib/components/login/widget/body/login_body_widget.dart, lib/components/sign_up/widget/body/sign_up_body_widget.dart, lib/shared/bloc/authentication_services/authentication_services_cubit.dart, lib/shared/repositories/app_authentication_repository.dart, lib/shared/repositories/auth_provider_module.dart, lib/shared/repositories/authentication_repository.dart, lib/shared/repositories/i_app_authentication_repository.dart, lib/shared/widget/button_additional_widget.dart, lib/shared/widget/sign_up_login_bottom_buttons_widget.dart, macos/Flutter/GeneratedPluginRegistrant.swift, pubspec.lock, pubspec.yaml, test/bloc/authentication_services_cubit_unit_test.dart, test/helpers/widget/language_switcher_helper.dart, test/helpers/widget/menu_dialog_helper.dart, test/mob_settings/helper/mob_settings_feedback_helper.dart, test/mob_settings/helper/mob_settings_initial_helper.dart, test/repository/app_authentication/app_authentication_repository_success_not_web_test.dart, test/repository/app_authentication/app_authentication_repository_success_test.dart, test/repository/app_authentication/app_authetication_failure_get_repository_test.dart, test/repository/app_authentication/app_authetication_failure_repository_test.dart, test/test_dependency_injector.dart, test/test_mocks/test_repository_mocks.dart
=> feat: apple authentication

lib/components/login/widget/body/login_body_widget.dart, lib/components/sign_up/widget/body/sign_up_body_widget.dart, lib/shared/bloc/authentication_services/authentication_services_cubit.dart, lib/shared/bloc/authentication_services/authentication_services_state.dart, lib/shared/repositories/app_authentication_repository.dart, lib/shared/repositories/authentication_repository.dart, test/bloc/authentication_services_cubit_unit_test.dart
=> feat: google sign in and apple show message when use sign in

lib/components/feedback/widget/bloc_listener/feedback_bloc_listener.dart, lib/components/login/widget/bloclistener/bloclistener.dart, lib/components/login/widget/bloclistener/login_bloclistener.dart, lib/components/login/widget/blocprovider/blocprovider.dart, lib/components/login/widget/body/body.dart, lib/components/login/widget/body/login_body_widget.dart, lib/components/login/widget/widget.dart, lib/components/sign_up/widget/bloclistener/bloclistener.dart, lib/components/sign_up/widget/bloclistener/sign_up_bloclistener.dart, lib/components/sign_up/widget/blocprovider/blocprovider.dart, lib/components/sign_up/widget/body/body.dart, lib/components/sign_up/widget/body/sign_up_body_widget.dart, lib/components/sign_up/widget/widget.dart, lib/components/story_add/widget/body/story_add_body.dart, lib/shared/constants/style/text_styles.dart, lib/shared/extension/extension_flutter_constants.dart, lib/shared/widget/dialogs_widget.dart
=> feat: new message for authenticaiont use google or apple only for mobile

README.md, android/app/src/main/AndroidManifest.xml, assets/markdown/terms_conditions_uk.md, ios/Runner/Runner.entitlements, lib/shared/constants/text/text_constants.dart
=> feat: deep linking use veteranam info url

pubspec.yaml
=> feat: mobile new version

lib/shared/data_provider/firebase_anaytics_cache_controller.dart, lib/shared/widget/mob_navigation_widget.dart
=> feat: android show cookie dialog

lib/components/discounts/bloc/config/discount_config_cubit.dart, lib/components/discounts/bloc/config/discount_config_state.dart, lib/components/discounts/widget/advanced_filter/advanced_filter_content.dart, lib/shared/widget/check_point_widget.dart, pubspec.yaml, test/discounts/unit_test/discount_config_cubit_test.dart
=> feat: mobile show count firebase config switcher

android/app/build.gradle, android/settings.gradle
=> feat: google ads fix android configuration

lib/shared/data_provider/firebase_analytics_provider.dart
=> feat: setConsent add ads parameter

ios/Runner/Info.plist, lib/shared/data_provider/firebase_analytics_provider.dart
=> feat: ios consent false as default

lib/components/discounts/widget/body/discounts_body_widget.dart, lib/shared/widget/mobile_ads_banner.dart
=> feat: check banner size after create ads banner

lib/shared/constants/route_constants.dart, lib/shared/navigation/router_go_mob.dart, lib/shared/repositories/url_repository.dart, pubspec.yaml
=> feat: unkown link redirect to discounts page

lib/shared/extension/extension_constants.dart
=> feat: add width for image optimization
